apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: log-web
spec:
  serviceAccountName: popeye-sa
  containers:
  - name: alpine
    image: alpine
    securityContext:
     readOnlyRootFilesystem: false
    command: ["/bin/sh","-c"]
    args: ["sleep 15; sh /mnt/script.sh; sleep infinity"]
    resources:
      requests:
        cpu: 1
        memory: 2Gi
    volumeMounts:
    - name: setup
      mountPath: /mnt
      readOnly: false
    - name: shared-data
      mountPath: /opt

  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: setup
    configMap:
      name: setup-script
  - name: shared-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: log-web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations: {}
#   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: popeye-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80