apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: popeye-dev
data:
  script.sh: |
    #!/bin/bash
    echo "Script Started Now"
    echo "Installing Git"
    apk add git 
    git --version
    sleep 5
    echo "Installing Go"
    apk add go 
    go version
    sleep 5
    cd ..
    echo "Clonning the Popeye Repo"
    git clone https://github.com/derailed/popeye 
    sleep 5
    cd popeye/
    echo "Installing popeye"
    go install
    sleep 5
    echo "Execute Popeye"
    go run main.go --out html > /opt/index.html
    echo "Procces Done!"