apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: popeye-crb
subjects:
  - kind: ServiceAccount
    name: popeye-sa
    namespace: popeye-dev
roleRef:
  kind: ClusterRole
  name: popeye-cr
  apiGroup: rbac.authorization.k8s.io
